version: "3"

services:
  server:
    build:
      context: ./.build
      args:
        TSHOCK_VERSION: 4.3.26
    image: senops.dev/senraria:latest
    container_name: senopsdev__senraria
    volumes:
      - ./data/world:/world
      - ./data/config:/config
      - ./data/logs:/logs
      - ./data/plugins:/plugins
    ports:
      - 7777:7777
    environment:
      AUTOCREATE: 1
      AUTOCREATE_WORLD_SIZE: 3
      WORLD_NAME: senraria